name: dart_feed
description: A simple RSS 2.0 feed reader library.
version: 0.0.1
author: Haran Kumar <hkumar8200@gmail.com>
homepage: https://github.com/harankumar/DartFeed
documentation:
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  xml: "^2.3.2"
  http: "^0.11.2"
dev_dependencies:
  test: '>=0.12.0 <0.13.0'